# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jDTW1KRmtMIU-r1DmZVQJ0KFtAi6ipa7
"""

import streamlit as st
import pickle
import numpy as np
from PIL import Image

# Load the trained model
import os

# Get the absolute path to the file
file_path = os.path.join(os.getcwd(), "pyfile.pk")

# Load the trained model
with open(file_path, "rb") as f:
    model = pickle.load(f)


# Define a function to perform style transfer
def style_transfer(content_image):
    # Your style transfer code here
    # You can use your model to perform style transfer
    # and return the resulting image
    return content_image

# Main function to run the Streamlit app
def main():
    st.title('Neural Style Transfer App')

    # Upload content image
    content_image = st.file_uploader('Upload Content Image', type=['jpg', 'png'])

    if content_image is not None:
        # Display content image
        st.image(content_image, caption='Content Image', use_column_width=True)

        # Perform style transfer when button is clicked
        if st.button('Transfer Style'):
            # Convert content image to numpy array
            content_image_np = np.array(Image.open(content_image))

            # Perform style transfer
            stylized_image = style_transfer(content_image_np)

            # Display stylized image
            st.image(stylized_image, caption='Stylized Image', use_column_width=True)

if __name__ == '__main__':
    main()

